### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by MikeGertrudes** [pricelinelabs/es-router#4]
Seeing some great contributions thus far, but linting doesn't seem to be part of the acceptance process. Either that or the linter is loose. Any way to do this? 

Namely the stylistic differences here:
- https://github.com/pricelinelabs/es-router/blob/master/src/es-router.js#L1
- https://github.com/pricelinelabs/es-router/blob/master/src/es-router.js#L5

**Comment by joshbDev** [comment]
this is fixed in https://github.com/pricelinelabs/es-router/pull/5. thanks for noticing!
